### ISSUE TITLE
CygbotParser.co does not compile

### ISSUE THREAD

**Issue by Tanay176** [CygLiDAR-ROS/cld1a0_pcl#26]
I've followed the instructions provided and I'm working with ROS Noetic on Ubuntu 20.04, however whenever executing the catkin_make command, I get the following error.

/home/i4/catkin_ws/src/cyglidar_d1/src/CygbotParser.c:40:16: error: cannot convert ‘uint8_t*’ {aka ‘unsigned char*’} to ‘Payload*’ {aka ‘Packet_Payload*’} in assignment
   40 |  pk->Payload = &CmdBuff[POS_PAYLOAD_HEADER];
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                |
      |                uint8_t* {aka unsigned char*}
make[2]: *** [cyglidar_d1/CMakeFiles/cyglidar_d1.dir/build.make:63: cyglidar_d1/CMakeFiles/cyglidar_d1.dir/src/CygbotParser.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1105: cyglidar_d1/CMakeFiles/cyglidar_d1.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j1" failed

Could you please advise on any change to be made to that file. I'm able to build the rest of the package files alright but this one prevents the make command from completing.

**Comment by mrezzaaa** [comment]
Same problem on macos with conda env

**Comment by amir-m2ai** [comment]
Hi @Tanay176,
Please check the issue "Error when running catking_make" here:
https://github.com/CygLiDAR-ROS/cyglidar_d1/issues/29
I have provided step-by-step instruction to make the package. 
I hope that resolves your issue.
